### ISSUE TITLE
ST_Area returns negative values

### ISSUE THREAD

**Issue by chaosmail** [Esri/spatial-framework-for-hadoop#110]
Hi guys,

When computing the Area of a single Polygon as MultiPolygon, the resulting area is negative.

```
SELECT
  ST_Area(ST_MultiPolygon(array(0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0)))
FROM src LIMIT 1;

>OK
> -1.0
> Time taken: 3.583 seconds, Fetched: 1 row(s)
```

When using a Polygon, it is working properly.

```
SELECT
  ST_Area(ST_Polygon(0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0))
FROM src LIMIT 1;
> OK
> 1.0
> Time taken: 0.845 seconds, Fetched: 1 row(s)
```

Best,
Christoph

**Comment by randallwhitman** [comment]
Thanks for reporting this - will need looking into.

**Comment by randallwhitman** [comment]
Contrast:
> select ST_Area(ST_MultiPolygon('multipolygon(((0.0 0.0, 1.0 0.0, 1.0 1.0, 0.0 1.0, 0.0 0.0)))'));
1.0
> select ST_Area(ST_MultiPolygon(array(0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0)));
1.0

**Comment by randallwhitman** [comment]
In ST_Polygon, obviate ordering/orientation issues constructing from number pairs, by generating WKT.
We could do the same in ST_MultiPolygon.
comments @climbage ?

**Comment by climbage** [comment]
Seems reasonable

**Comment by randallwhitman** [comment]
Also, ST_MultiPolygon erroneously sets y=x for the first point listed.
> select ST_AsText(ST_MultiPolygon(array(0.0, 1.0, 1.0, 1.0, 1.0, 0.0)));
MULTIPOLYGON (((0 0, 1 0, 1 1, 0 0)))
