### ISSUE TITLE
One problem about how to compute the distance from point to polygon boundary when point in polygon

### ISSUE THREAD

**Issue by hengshanji** [Esri/spatial-framework-for-hadoop#125]
I want to compute the distance from point to polygon boundary when this point in polygon. This task need compute the distance from point to line ,or linestring. I find a method to do this. First use ST_ExteriorRing get the linestring of  polygon. but i need remove one point, so the linestring is not a polygon anymore. then compute two times of point to linestring , and find the smaller distance . it will be the smallest distance of point to polygon when point in polygon.

I need a method to remove one point of a polygon's linestring. Could someone tell me how to do this? i will be very appreciated!

**Comment by randallwhitman** [comment]
Not understanding what would be missing from simply:
`select ST_Distance(ST_ExteriorRing(ST_Polygon(-1,-1, 1,-1, 1,1, -1,1)), ST_Point(0.2,0.5));`
