### ISSUE TITLE
Making a circle geometry with ST_Buffer giving a radius in meter

### ISSUE THREAD

**Issue by namiokan** [Esri/spatial-framework-for-hadoop#129]
Hello,
I want to make a circle geometry giving a radius in meter like this:

`select st_buffer(st_setsrid(st_point(130.705638, 32.819381), 4326), 457);`

However it seems st_buffer returns circle with its radius in lon/lat.
Does st_buffer only deal with lat/lon? Is there any way to give radius in meter?
There is few description about st_buffer in the documentation.

Any response will be appreciated. Thank you!

**Comment by climbage** [comment]
What you're looking for is a [geodesic buffer](http://www.esri.com/news/arcuser/0111/geodesic.html) which is not supported in the geometry library used by the ST functions.

**Comment by namiokan** [comment]
@climbage Thank you for your reply. I will try another way (or define my own function).
Thank you very much!
