### ISSUE TITLE
JSON SerDe Compile Error with Hive-2.3

### ISSUE THREAD

**Issue by randallwhitman** [Esri/spatial-framework-for-hadoop#130]
`mvn clean test -Phive-2.3`
```
[ERROR] /net/domus/domus1/users/r/rand7186/Supernova/spatial-framework-for-hadoop/hive/src/main/java/com/esri/hadoop/hive/serde/BaseJsonSerDe.java:[14,36] error: cannot find symbol
[ERROR]  package org.apache.hadoop.hive.serde2
/net/domus/domus1/users/r/rand7186/Supernova/spatial-framework-for-hadoop/hive/src/main/java/com/esri/hadoop/hive/serde/BaseJsonSerDe.java:[51,47] error: cannot find symbol
```

**Comment by randallwhitman** [comment]
[HIVE-15167](https://issues.apache.org/jira/browse/HIVE-15167), [HIVE-4007](https://issues.apache.org/jira/browse/HIVE-4007)
https://github.com/apache/hive/commit/652ed7a796c687bbb3aff0504a5f91ee685eaab9#diff-
50cd1588e918e5d74a4711dd3743c6ec
Any objection to requiring Hive v0.11+ for Spatial Framework v2.0+ ?  @climbage @smambrose

**Comment by climbage** [comment]
No objections here.
