### ISSUE TITLE
Tranforming array<array<double>> to ST_MultiPolygon

### ISSUE THREAD

**Issue by Andarius** [Esri/spatial-framework-for-hadoop#132]
I'm trying to load a valid Geojson file using SPARK SQL and then transforming the coordinates to ST_MultiPolygon.

The jars I use are:
```
esri-geometry-api-2.0.0.jar
spatial-sdk-json-1.2.0.jar
spatial-sdk-hive-1.2.0.jar
```

The schema of the input data is:

```
 |-- geometry: struct (nullable = true)
 |    |-- coordinates: array (nullable = true)
 |    |    |-- element: array (containsNull = true)
 |    |    |    |-- element: array (containsNull = true)
 |    |    |    |    |-- element: array (containsNull = true)
 |    |    |    |    |    |-- element: double (containsNull = true)
 |    |-- type: string (nullable = true)
 |-- properties: struct (nullable = true)
 |-- type: string (nullable = true)
```

The process fails when I try the following: 
```
SELECT
    st_multipolygon(geometry.coordinates[0][0]) as geo
FROM test
```
I get:

`No handler for Hive UDF 'com.esri.hadoop.hive.ST_MultiPolygon': org.apache.hadoop.hive.ql.exec.NoMatchingMethodException: No matching method for class com.esri.hadoop.hive.ST_MultiPolygon with (array<array<double>>). Possible choices: _FUNC_(array<array<double>>)  _FUNC_(string)  ; `

So I pass an **array<array<double>>** and it expects an **array<array<double>>**.

It works if I try:
```
SELECT
    st_multipolygon(geometry.coordinates[0][0][0], geometry.coordinates[0][0][1], ...) as geo
FROM test
```

Any idea of what's wrong (or what I'm doing wrong ?)

**Comment by randallwhitman** [comment]
Spatial-Framework documentation says [ST_MultiPolygon(array(x1, y1, x2, y2, ... ), array(x1, y1, x2, y2, ... ), ... )](https://github.com/Esri/spatial-framework-for-hadoop/wiki/UDF-Constructors#st_multipolygon), so it looks like `st_multipolygon(geometry.coordinates[0][0][0], geometry.coordinates[0][0][1], ...)` passes array&lt;double&gt; as expected and works correctly.

Maybe the only oddity is - is Spark-SQL presenting a botched error message?

**Comment by randallwhitman** [comment]
Cross-reference #36, #126.

**Comment by randallwhitman** [comment]
Try `ST_GeomFromGeoJson`.
