### ISSUE TITLE
Error while executing hive query 'com.esri.json.hadoop.EnclosedEsriJsonInputFormat'

### ISSUE THREAD

**Issue by pchauhan2** [Esri/spatial-framework-for-hadoop#134]
We are using hive 1.x and our spatial frameworks were working earlier, i have added the jars but i am facing this issue while executing 'drop '

**Comment by randallwhitman** [comment]
The 'd' is missing in "Enclosed".

**Comment by pchauhan2** [comment]
what does that signify ?
We are running this code https://github.com/Esri/gis-tools-for-hadoop/tree/master/samples/point-in-polygon-aggregation-hive  , it used to work earlier

**Comment by randallwhitman** [comment]
The title says "Error while executing hive query 'com.esri.json.hadoop.EncloseEsriJsonInputFormat'" - if that was cut and pasted, it indicates a missing 'd' in the input format of the table.

**Comment by pchauhan2** [comment]
Understood let me check that and get back to you 
Thanks

**Comment by pchauhan2** [comment]
No 'd' misssing the error is SemanticException Cannot find class 'com.esri.json.hadoop.EnclosedEsriJsonInputFormat'

**Comment by randallwhitman** [comment]
What versions of Spatial Framework for Hadoop, Esri Geometry, Hive, and Hadoop?

**Comment by pchauhan2** [comment]
It was installed by the  previous team, any idea how can i check the version of framework , for hive it is 1.x, HDP 2.5.3(hortonworks)

**Comment by randallwhitman** [comment]
For Spatial Framework, it may have been either built from scratch or downloaded as JAR files.  If downloaded as JAR files, you can try to match timestamp, filesize, and or MD5 checksums with the [releases](https://github.com/Esri/spatial-framework-for-hadoop/releases).

**Comment by pchauhan2** [comment]
They were downloaded as JAR files, 
 can you kindly elaborate MD5 checksums ? @randallwhitman

**Comment by randallwhitman** [comment]
Please consult a web search engine to find information on checksums.
