### ISSUE TITLE
hexagon binning

### ISSUE THREAD

**Issue by geoHeil** [Esri/spatial-framework-for-hadoop#143]
https://github.com/Esri/spatial-framework-for-hadoop/blob/1ed3d421eb5c062a5309f6c610cd646210daf889/hive/src/main/java/com/esri/hadoop/hive/BinUtils.java does not seem to use hexagon binning I am used from acrGIS - are there plans to implement this?

**Comment by randallwhitman** [comment]
The Spatial-framework-for-Hadoop is open-source and [contributions are welcome](https://github.com/Esri/spatial-framework-for-hadoop/blob/master/CONTRIBUTING.md).

**Comment by randallwhitman** [comment]
FWIW - https://github.com/Esri/gis-tools-for-hadoop/blob/altcalcs/samples/trip-discovery/src/com/esri/hadoop/examples/trip/HexagonMesh.java

**Comment by geoHeil** [comment]
Many thanks ,great
