### ISSUE TITLE
The accuracy of the BoundaryShape binary field is problematic

### ISSUE THREAD

**Issue by rarewei** [Esri/spatial-framework-for-hadoop#151]
I use GeoJson to create a table.
![default](https://user-images.githubusercontent.com/15240926/39862995-ec85ef56-5477-11e8-90be-3ac7e939d1b8.png)
GeoJson like this:
![default](https://user-images.githubusercontent.com/15240926/39863089-3aeadd00-5478-11e8-8cf8-5aee169ba300.png)
But using Hive ST_ASTEXT function, the result is less than one bit。like this
POLYGON ((104.76771238499998 26.762176599999975,

so how to fix that?

**Comment by randallwhitman** [comment]
Is the difference more than, or less than, the tolerance of the spatial reference?

**Comment by rarewei** [comment]
Sorry...I mean after loading the data into Hive by that function,my result is 1 bit less than original data.
This affects the correctness of intersect results.

**Comment by randallwhitman** [comment]
What is the absolute error?  What is the relative error?  I don't see numbers that can be copy-pasted into a calculator.

**Comment by randallwhitman** [comment]
Absent additional information, this is assumed to related to floating-point roundoff and not affect the result more than the spatial-reference tolerance.
