### ISSUE TITLE
Error Loading Json into the table

### ISSUE THREAD

**Issue by TayyabMir56** [Esri/spatial-framework-for-hadoop#156]
Hi.
I'm following your tutorial "[Aggregation Sample for Hive](https://github.com/Esri/gis-tools-for-hadoop/tree/master/samples/point-in-polygon-aggregation-hive)" 
Using the LOAD DATA INPATH Command, Following is my ouput
![image](https://user-images.githubusercontent.com/6566554/42156646-0b58805e-7e05-11e8-9d48-887819b7fbe1.png)
To be noted: numRows = 0

When I query this table it shows junk value
Query: SELECT * FROM counties LIMIT 100;
Output:

![image](https://user-images.githubusercontent.com/6566554/42156913-bd09cee8-7e05-11e8-88eb-11079d6219dd.png)

This did not happen when I followed the tutorial with the previous version of JAR files a few months back.

Please inform me what am I doing wrong here, although I'm just copy pasting the queries.

Regards
Tayyab

**Comment by climbage** [comment]
What you're seeing is the binary representation of `BoundaryShape`. You need to use `ST_AsText` to convert to a human readable format. 

```sql
create temporary function ST_AsText as 'com.esri.hadoop.hive.ST_AsText';
select st_astext(BoundaryShape) from counties;
```

**Comment by TayyabMir56** [comment]
My bad.
Many Thanks for the quick response.
