### ISSUE TITLE
ST_Contains Could not parse Well-Known Text around position: 0 and invalid shape type

### ISSUE THREAD

**Issue by kullaibigdata** [Esri/spatial-framework-for-hadoop#160]
Hi,

For the spatial hive quiries I am using below jars.

add jar /home/hdfs/esri-geometry-api.jar;
add jar /home/hdfs/spatial-sdk-hive-1.1.1-SNAPSHOT.jar;
add jar /home/hdfs/spatial-sdk-json-1.1.1-SNAPSHOT.jar;

Hive version : 2.3.4

1) When I execute the below query getting error like "Could not parse Well-Known Text around position: 0 " and geom,interpolated_geom data type is string

hive> select * from demo.spatial_table where ST_Contains(geom,interpolated_geom) = 't' limit 10;
OK
Failed with exception java.io.IOException:java.lang.IllegalArgumentException: Could not parse Well-Known Text around position: 0
Time taken: 0.311 seconds

2) When I execute the below query getting error like  "invalid shape type"  this time creating geom,interpolated_geom data type is binary

hive> select * from demo.spatial_table where ST_Contains(geom,interpolated_geom) = 't' limit 10;
OK
Failed with exception java.io.IOException:com.esri.core.geometry.GeometryException: invalid shape type
Time taken: 0.213 seconds

Could you please advise anyone to solve this problem.

Thanks & Regards,
Kullaireddy N.

**Comment by randallwhitman** [comment]
[For Hive-2.3+](https://github.com/Esri/spatial-framework-for-hadoop/wiki/ST_Geometry-for-Hive-Compatibility-with-Hive-Versions), please [upgrade to v2 of the Spatial Framework for Hadoop](https://github.com/Esri/spatial-framework-for-hadoop/releases).

**Comment by kullaibigdata** [comment]
Hi Randallwhitman,

I upgrade as per your suggestion and I do R&D on this issue still i can't figure out.

I am running below query like this.

select * from demo.spatial_table  a JOIN demo.spatial_table_1 b ON (a.id=b.id) where ST_Contains(ST_Polygon(b.interpolatedgeomxy_output),ST_Point(2,3)) limit 1;

I got a error like this:
Exception in thread "main" org.apache.hive.com.esotericsoftware.kryo.KryoException: Unable to find class: com.esri.hadoop.hive.ST_Contains

I created temporary function.

Please advise for the same.

**Comment by randallwhitman** [comment]
That's certainly a different error than before, and it looks like the entire stack trace is Apache Hive code, not code in Esri Spatial Framework for Hadoop.  Do either of the workarounds for a previous Hive version (Esri/gis-tools-for-hadoop#9) change anything:
* copy the JAR files for Spatial-Framework-for-Hadoop and Geometry-API-Java to $HIVE_HOME/lib ;
* `env HADOOP_CLASSPATH=esri-geometry-api.jar:spatial-sdk-hadoop.jar hive ...`
?

**Comment by kullaibigdata** [comment]
Hi Randallwhitman,

Thanks for response it's working fine.Please close this ticket.

Thanks & Regards,
Kullaireddy N

**Comment by kullaibigdata** [comment]
@ @
