### ISSUE TITLE
Are the UDFs supported on impala?

### ISSUE THREAD

**Issue by reason1241** [Esri/spatial-framework-for-hadoop#162]
I'd like to use the spatial udfs like ST_Contains or ST_Point etc on impala with Cloudera.

But the impala says like 

ERROR: AnalysisException: Failed to load metadata for table: 'table'
CAUSED BY: TableLoadingException: Unrecognized table type for table: test.table

Is there any way that I can use these udf on impala?

**Comment by randallwhitman** [comment]
These spatial UDFs should be usable on any system with complete support for Hive UDFs.  We maintainers have tested in SparkSQL, but have no Impala installation on which to test.

Maybe someone else has tried on Impala and can comment.
Do you have on hand a reference as to Impala compatibility/support with/for Hive UDFs?
Have you tried the same query on Hive or on SparkSQL?

**Comment by reason1241** [comment]
I've tried to apply the UDF at Impala but it doesn't work.
I guess Impala does not support the internal operations of the UDF.
