### ISSUE TITLE
How to convert from wkb string to geometry type?

### ISSUE THREAD

**Issue by myskbj** [Esri/spatial-framework-for-hadoop#168]
I have wkb of type string in hive table
 (ex. "0106000020E03000000010000007218000007000060B1D4")

How to convert from wkb string to geometry type using udf function?

**Comment by randallwhitman** [comment]
Please see [`ST_GeomFromWKB`](https://github.com/Esri/spatial-framework-for-hadoop/wiki/UDF-Documentation#constructors)
