### ISSUE TITLE
ST_BinGeometry does not work with Decimal in Hive 2.3

### ISSUE THREAD

**Issue by kash159** [Esri/spatial-framework-for-hadoop#171]
https://github.com/Esri/spatial-framework-for-hadoop/pull/170

Error: Error while compiling statement: FAILED: SemanticException [Error 10014]: Line 1:12 Wrong arguments 'geometry': Argument 0 must be a number (state=42000,code=10014)

**Comment by kash159** [comment]
@randallwhitman

**Comment by randallwhitman** [comment]
Hi @kash159 - would you like to provide a patch like #170 & #164?

**Comment by kash159** [comment]
#170 fixed this issue. Closing issue. Can a new version be released ?

**Comment by randallwhitman** [comment]
As for releasing a new version, it would be nice if we could figure out Esri/gis-tools-for-hadoop#83
