### ISSUE TITLE
An exception occurred while creating a table using Esrijsonserde

### ISSUE THREAD

**Issue by 1012170459** [Esri/spatial-framework-for-hadoop#172]
hive version:0.13.0
spatial-framework-for-hadoop version:2.1.0
After building, an exception occurred when importing the jar package according to the tutorial
The abnormal information is:   exec.DDLTask (DDLTask.java:execute(478)) - java.lang.NoClassDefFoundError: com/fasterxml/jackson/core/JsonProcessingException

**Comment by randallwhitman** [comment]
Hi - please make sure that Jackson is in the classpath.  (And take note of recent patch levels after posted vulnerabilities.)

**Comment by 1012170459** [comment]
Thank you. The problem has been solved
