### ISSUE TITLE
HI，How to support the direct import of geojson

### ISSUE THREAD

**Issue by 1012170459** [Esri/spatial-framework-for-hadoop#173]
The currently supported JSON format is the standard format of ESRI JSON. If I want to import geojson directly, do I need to rewrite inputformat, outputformat and serde? If so, do I need to pay attention to it? Thank you

**Comment by randallwhitman** [comment]
Spatial Framework for Hadoop has InputFormat and SerDe for GeoJSON as of v1.2 onward (though strongly recommend v2.x).
