### ISSUE TITLE
permission denied error for the spatial function "st_aggr_union"

### ISSUE THREAD

**Issue by bgajula** [Esri/spatial-framework-for-hadoop#179]
Hi,

I am trying to use st_aggr_union function using a permanent UDF created on hive. 
Used the following command to create it 

DROP FUNCTION IF EXISTS udf_db.st_aggr_union;
CREATE FUNCTION p0_bcc_eudswr.st_aggr_union AS 'com.esri.hadoop.hive.ST_Aggr_Union' USING JAR 'hdfs://user/esri/lib/spatial-sdk-hive-2.1.0.jar';

when running the udf against the spatial data, I am getting bellow error 

Error: Error while compiling statement: FAILED: HiveAccessControlException Permission denied: user [userxxxx] does not have [SELECT] privilege on [@_udf_db/st_aggr_union] (state=42000,code=40000)

We have created many other spatial functions and using them without any issues. 

Could you please help me with this.

**Comment by randallwhitman** [comment]
* Does the error happen with the other aggregate functions, such as aggregate convex hull or aggregate intersection?
* Does the error happen when running the query as the Hive super-user (for testing)?
* What happens if you CREATE FUNCTION st_aggr_union without `p0_bcc_eudswr.` in front?

**Comment by bgajula** [comment]
Hi,

Does the error happen with the other aggregate functions, such as aggregate convex hull or aggregate intersection? --> It is happening with other two aggregate functions as well
Does the error happen when running the query as the Hive super-user (for testing)? --> This is yet to be checked. I will update on this
What happens if you CREATE FUNCTION st_aggr_union without p0_bcc_eudswr. in front?  --> This is happening irrespective of the DB.
