### ISSUE TITLE
README image is broken

### ISSUE THREAD

**Issue by jholycross** [Esri/spatial-framework-for-hadoop#191]
README refers to 
https://travis-ci.org/Esri/spatial-framework-for-hadoop.png?branch=master
which does not appear to be publicly available

**Comment by randallwhitman** [comment]
Thanks for pointing that out.
Fixed by removing the link - https://github.com/Esri/spatial-framework-for-hadoop/commit/7226df669cbfaaf1edbfac0461acd1af45e12b81
