### ISSUE TITLE
got error when packaging it says "sample-study-area.json does not exist"...

### ISSUE THREAD

**Issue by Leospearo** [Esri/spatial-framework-for-hadoop#194]
spatial-framework-for-hadoop-master/json/target/test-classes/com/esri/json/hadoop/sample-study-area.json does not exist
	at org.apache.hadoop.fs.RawLocalFileSystem.deprecatedGetFileStatus(RawLocalFileSystem.java:641)
	at org.apache.hadoop.fs.RawLocalFileSystem.getFileLinkStatusInternal(RawLocalFileSystem.java:867)
	at org.apache.hadoop.fs.RawLocalFileSystem.getFileStatus(RawLocalFileSystem.java:631)
	at org.apache.hadoop.fs.FilterFileSystem.getFileStatus(FilterFileSystem.java:442)
	at org.apache.hadoop.fs.ChecksumFileSystem$ChecksumFSInputChecker.<init>(ChecksumFileSystem.java:146)

**Comment by randallwhitman** [comment]
Hi @Leospearo - thanks for reporting that.  Could you share the complete exact command line you used?  (for me `mvn package` succeeded.)

**Comment by Leospearo** [comment]
> Hi @Leospearo - thanks for reporting that. Could you share the complete exact command line you used? (for me `mvn package` succeeded.)

Of course, after I installed the dependencies, I clicked on the package directly, as shown in the image
![Uploading iShot_2024-06-22_20.28.32.png…]()

**Comment by Leospearo** [comment]
<img width="1045" alt="iShot_2024-06-22_20 28 32" src="https://github.com/Esri/spatial-framework-for-hadoop/assets/63917432/a2ce2ca9-eb5f-4ff9-a559-7b5718ed9312">

**Comment by randallwhitman** [comment]
So not from a command line, but from some GUI, which I am not familiar.
I would assume that the GUI generates some command line upon the button press.  Maybe the GUI app will let you capture the command line it generates, for copy-paste.

**Comment by Leospearo** [comment]
> So not from a command line, but from some GUI, which I am not familiar. I would assume that the GUI generates some command line upon the button press. Maybe the GUI app will let you capture the command line it generates, for copy-paste.

OK, I got error after commit the command "mvn package"
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.esri.json.hadoop.TestUnenclosedEsriJsonRecordMrv1
ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console.
log4j:WARN No appenders could be found for logger (org.apache.htrace.core.Tracer).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Tests run: 12, Failures: 0, Errors: 12, Skipped: 0, Time elapsed: 1.348 sec <<< FAILURE!
Running com.esri.json.hadoop.TestEnclosedEsriJsonRecordReader
Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.015 sec <<< FAILURE!
Running com.esri.json.hadoop.TestEnclosedGeoJsonRecordReader
Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.009 sec <<< FAILURE!
Running com.esri.json.hadoop.TestUnenclosedGeoJsonRecordReader
Tests run: 3, Failures: 0, Errors: 3, Skipped: 0, Time elapsed: 0.032 sec <<< FAILURE!
Running com.esri.json.hadoop.TestUnenclosedEsriJsonRecordReader
Tests run: 12, Failures: 0, Errors: 12, Skipped: 0, Time elapsed: 0.077 sec <<< FAILURE!

**Comment by randallwhitman** [comment]
Hmm, not sure where one would start troubleshooting or debugging, if it suceeds for me.  What version of Maven and JDK are you using?  (i have maven-3.6.3 and OpenJDK-8 on Ubuntu-20.04/Linux.)

If you would like to try to run the tests without troubleshooting the file-not-found error, it *might* work to run:
`cp json/src/test/resources/com/esri/json/hadoop/sample-study-area.json json/target/test-classes/com/esri/json/hadoop/sample-study-area.json`

If you want to build the JAR files without needing to run the tests, maybe `mvn -DskipTests package` or `mvn -Dmaven.test.skip=true package` .
___

`env JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64 mvn -o -B clean package >& mvn-pkg.out`

```
[INFO] Spatial Framework for Hadoop ....................... SUCCESS [  0.098 s]
[INFO] Spatial JSON Utilities ............................. SUCCESS [  7.165 s]
[INFO] Spatial Framework for Hive and SparkSQL ............ SUCCESS [  5.945 s]
```

**Comment by Leospearo** [comment]
> Hmm, not sure where one would start troubleshooting or debugging, if it succeeds for me. What version of Maven and JDK are you using? (i have maven-3.6.3 and OpenJDK-8 on Ubuntu-20.04/Linux.)
> 
> If you would like to try to run the tests without troubleshooting the file-not-found error, it _might_ work to run: `cp json/src/test/resources/com/esri/json/hadoop/sample-study-area.json json/target/test-classes/com/esri/json/hadoop/sample-study-area.json`
> 
> If you want to build the JAR files without needing to run the tests, maybe `mvn -DskipTests package` or `mvn -Dmaven.test.skip=true package` .
> 
> `env JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64 mvn -o -B clean package >& mvn-pkg.out`
> 
> ```
> [INFO] Spatial Framework for Hadoop ....................... SUCCESS [  0.098 s]
> [INFO] Spatial JSON Utilities ............................. SUCCESS [  7.165 s]
> [INFO] Spatial Framework for Hive and SparkSQL ............ SUCCESS [  5.945 s]
> ```
Thanks, I packed it successfully.
