### ISSUE TITLE
JsonSerde.java serialization and deserialization skips the spatial reference information

### ISSUE THREAD

**Issue by stolstov** [Esri/spatial-framework-for-hadoop#39]

**Comment by amitabh74** [comment]
Following is the syntax followed for creating the table - 
CREATE TABLE agg_samp(area binary, count double)
ROW FORMAT SERDE 'com.esri.hadoop.hive.serde.JsonSerde'              
STORED AS INPUTFORMAT 'com.esri.json.hadoop.EnclosedJsonInputFormat'
OUTPUTFORMAT 'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat';

how can i extract the data in JSON format specially the binary information that stores the geometry?
I have tried using java api for hive2 but it returns junk characters.

**Comment by randallwhitman** [comment]
Hi - does this question relate to SpatialReference?  Assuming that it does not, please open a new issue for the new question?

**Comment by amitabh74** [comment]
No it doesn't relate to SpatialReference. I will open a new issue.
