### ISSUE TITLE
Anyway to search in hive by distance from point?

### ISSUE THREAD

**Issue by amartira** [Esri/spatial-framework-for-hadoop#53]
Sorry about this issue because it isn't a real issue, but i can't find in documentation the way to search points within a distance from center point.

I searched in google for this, but few people use this library and there are few examples.

Please provide me a solution here or at: andresmrazola@gmail.com

Thank you for your incredible job!!

**Comment by ad8700** [comment]
I have 2 tables, a and b. each has the format 

> id|latitude|longitude

I'm trying to get if any address in b is within a given radius from any location in a, write that distance to b in a new column.  What should I plug in to (centre[0], centre[1], table.coordinate[0], table.coordinate[1])?

**Comment by randallwhitman** [comment]
See ST-LineString constructor doc:
https://github.com/Esri/spatial-framework-for-hadoop/wiki/UDF-Constructors#st_linestring

**Comment by ad8700** [comment]
Sorry, but I don't understand the ST_Linestring constructor......

**Comment by climbage** [comment]
@ad8700 Please create a new issue for this question or ask over at www.stackoverflow.com or www.gis.stackexchange.com using the `[hadoop]` tag.
