### ISSUE TITLE
ST_Point is not working on Hive Query

### ISSUE THREAD

**Issue by dharmeshpurohit** [Esri/spatial-framework-for-hadoop#69]
I am trying to use ST_Point on HIve query but ST_Point is giving me following error whereas other functions are working fine.

Error occurred executing hive query: OK converting to local hdfs://ns/user/dp11317/spatial-sdk-hive-1.0.2.jar Added /tmp/64dc10a2-b180-46d2-8242-acdcdac2f903_resources/spatial-sdk-hive-1.0.2.jar to class path Added resource: /tmp/64dc10a2-b180-46d2-8242-acdcdac2f903_resources/spatial-sdk-hive-1.0.2.jar converting to local hdfs://ns/user/dp11317/spatial-sdk-json-1.0.2.jar Added /tmp/64dc10a2-b180-46d2-8242-acdcdac2f903_resources/spatial-sdk-json-1.0.2.jar to class path Added resource: /tmp/64dc10a2-b180-46d2-8242-acdcdac2f903_resources/spatial-sdk-json-1.0.2.jar converting to local hdfs://ns/user/dp11317/esri-geometry-api-1.2.jar Added /tmp/64dc10a2-b180-46d2-8242-acdcdac2f903_resources/esri-geometry-api-1.2.jar to class path Added resource: /tmp/64dc10a2-b180-46d2-8242-acdcdac2f903_resources/esri-geometry-api-1.2.jar OK FAILED: SemanticException [Error 10014]: Line 1:7 Wrong arguments '1': The UDF implementation class 'com.esri.hadoop.hive.ST_Point' is not present in the class path

Some side notes : 

I am using Hortonworks with Hive 0.13

- Dharmesh

**Comment by randallwhitman** [comment]
If there is additional information, go ahead and re-open the issue.

**Comment by serenasignorelli** [comment]
Hello everybody, 

I know a lot of time has passed since the last comment here, but I'm having the same error as @dharmeshpurohit. 

This is the query I want to run:

SELECT u.*, n.boroname, n.borocode 
FROM prova100 u
JOIN nyc_geobin n 
WHERE ST_Contains(n.shape, ST_Point(u.pickup_longitude, u.pickup_latitude));

and this is the error I'm getting:

Error while compiling statement: FAILED: SemanticException [Error 10014]: Line 4:27 Wrong arguments 'pickup_latitude': Unable to instantiate UDF implementation class com.esri.hadoop.hive.ST_Point: java.lang.IllegalAccessException: Class org.apache.hadoop.hive.ql.udf.generic.GenericUDFBridge can not access a member of class com.esri.hadoop.hive.ST_Point with modifiers ""

I have the latest versions of the jar files, so I can't understand where the error is. 

Any ideas?

Thank you,

Serena

**Comment by serenasignorelli** [comment]
Maybe I'm completely wrong, but could it be a problem that `ST_Point extends ST_Geometry` which `extends UDF` rather than `extends GenericUDF`?

**Comment by randallwhitman** [comment]
Hi @serenasignorelli : when you say you have the latest version, which do you mean:
* You built from source code on master;
* You downloaded the v1.2.0 JAR files from Github;
* You got v1.1 via Maven (I haven't yet manged to get v1.2.0 onto maven central)?

What versions of Hive and Hadoop are you using?

**Comment by serenasignorelli** [comment]
Thank you @randallwhitman for the reply!

I downloaded the v1.2.0 JAR files from Github. I'm working with Hive 1.1.0-cdh5.10.0 and Hadoop 2.6.0-cdh5.10.0

**Comment by randallwhitman** [comment]
For me, `mvn clean test -Phive-1.1 -Phadoop-2.6` on master passed all automated tests.
(I have hadoop-2.6 but no deployment of hive-1.1 version.)

**Comment by randallwhitman** [comment]
@serenasignorelli If you like you can paste in details of your add-jar and add-temporary-function commands, and your schema (create-table commands) to see if that gives any ideas ..

**Comment by serenasignorelli** [comment]
Thank you @randallwhitman. I was trying to rerun everything, but now I'm getting another kind of error. This is the code I'm running:
`add jar hdfs://hadoop-cloudera1.hadoop.icteam.local:8020/data/samples/YELLOW_TAXI/spatial-sdk-hive-1.2.0.jar;
add jar hdfs://hadoop-cloudera1.hadoop.icteam.local:8020/data/samples/YELLOW_TAXI/spatial-sdk-json-1.2.0.jar;
add jar hdfs://hadoop-cloudera1.hadoop.icteam.local:8020/data/samples/YELLOW_TAXI/esri-geometry-api-1.2.1.jar;
add jar hdfs://hadoop-cloudera1.hadoop.icteam.local:8020/data/samples/YELLOW_TAXI/json-serde-1.3.6-SNAPSHOT-jar-with-dependencies.jar;
CREATE TEMPORARY FUNCTION ST_GeomFromGeoJson as 'com.esri.hadoop.hive.ST_GeomFromGeoJson';
CREATE TEMPORARY FUNCTION ST_Contains as 'com.esri.hadoop.hive.ST_Contains';
CREATE TEMPORARY FUNCTION ST_Point as 'com.esri.hadoop.hive.ST_Point';`
And I'm getting this error:
`INFO  : Compiling command(queryId=hive_20170425191212_ea608f63-f3b5-4997-ae02-b6afa6cf3d89): CREATE TEMPORARY FUNCTION ST_Contains as 'com.esri.hadoop.hive.ST_Contains'
INFO  : Semantic Analysis Completed
INFO  : Returning Hive schema: Schema(fieldSchemas:null, properties:null)
INFO  : Completed compiling command(queryId=hive_20170425191212_ea608f63-f3b5-4997-ae02-b6afa6cf3d89); Time taken: 0.001 seconds
INFO  : Executing command(queryId=hive_20170425191212_ea608f63-f3b5-4997-ae02-b6afa6cf3d89): CREATE TEMPORARY FUNCTION ST_Contains as 'com.esri.hadoop.hive.ST_Contains'
INFO  : Starting task [Stage-0:FUNC] in serial mode
ERROR : FAILED: Execution Error, return code -101 from org.apache.hadoop.hive.ql.exec.FunctionTask. com/esri/core/geometry/OperatorSimpleRelation
INFO  : Completed executing command(queryId=hive_20170425191212_ea608f63-f3b5-4997-ae02-b6afa6cf3d89); Time taken: 0.006 seconds`

**Comment by serenasignorelli** [comment]
I also tried to redownload the jar file from https://github.com/Esri/gis-tools-for-hadoop/releases 

Running this:

`add jar hdfs://hadoop-cloudera1.hadoop.icteam.local:8020/data/samples/YELLOW_TAXI/gis-tools-hadoop-2.0.jar;
CREATE TEMPORARY FUNCTION ST_Point as 'com.esri.hadoop.hive.ST_Point'`

I obtain again:

`Error while processing statement: FAILED: Execution Error, return code -101 from org.apache.hadoop.hive.ql.exec.FunctionTask. com/esri/core/geometry/Geometry`

**Comment by randallwhitman** [comment]
Offhand I'm not familiar with such Hive errors.  You might also try a web search and/or Hive or Cloudera forum about Hive errors -101, 10014, etc.

**Comment by serenasignorelli** [comment]
I cannot find anywhere someone with error -101.
The strange thing is that no errors occur running `CREATE TEMPORARY FUNCTION ST_GeomFromGeoJson as 'com.esri.hadoop.hive.ST_GeomFromGeoJson';`...

**Comment by randallwhitman** [comment]
Ideas: ask about Hive error on Cloudera forum, Hive forum/mail-list, StackOverflow ... ; search Hive source code for the error ..

**Comment by serenasignorelli** [comment]
Problem solved: I was working on Hue, I tried to switch to the command line... and everything works! I still haven't explored which is the problem on Hue, but at least I could run my code!
Thank you again for your time, @randallwhitman !

**Comment by randallwhitman** [comment]
That is good to know - thanks for the update @serenasignorelli .
Hue developers and/or Cloudera may be interested in the issues you encountered in Hue.

**Comment by serenasignorelli** [comment]
I am not an expert, so sorry if I'm saying something not in a perfect 'computer science language'. 
Some colleagues of mine suspect that the problem is not Hue itself, because I tried also through Toad and the same happens. 
The problem should be using Hive through 'beeline' (while now I'm using Hive from the command line through 'hive').

**Comment by randallwhitman** [comment]
Ah, that sounds like some good work to isolate the relevant component - so yeah, probably the Beeline project then.
