### ISSUE TITLE
ST_AsText functions are not working

### ISSUE THREAD

**Issue by vijayasarathib** [Esri/spatial-framework-for-hadoop#73]
i am getting the below error :

hive> add jar /users/vb4087/esri-geometry-api.jar ;
Added /users/vb4087/esri-geometry-api.jar to class path
Added resource: /users/vb4087/esri-geometry-api.jar
hive> add jar spatial-sdk-hive-1.0.1-sources.jar;
Added spatial-sdk-hive-1.0.1-sources.jar to class path
Added resource: spatial-sdk-hive-1.0.1-sources.jar
hive> add jar spatial-sdk-hadoop.jar;
Added spatial-sdk-hadoop.jar to class path
Added resource: spatial-sdk-hadoop.jar
hive> SELECT ST_Area(ST_Polygon(1,1, 1,4, 4,4, 4,1)) FROM vj_demo1 LIMIT 1;
FAILED: SemanticException [Error 10011]: Line 1:15 Invalid function 'ST_Polygon'

hive> SELECT ST_AsText(1,1, 1,4, 4,4, 4,1) FROM vj_demo1 limit 1;
FAILED: SemanticException [Error 10011]: Line 1:7 Invalid function 'ST_AsText'

**Comment by randallwhitman** [comment]
Hive also needs the temporary-function definitions, e.g.
```sql
create temporary function ST_AsText as 'com.esri.hadoop.hive.ST_AsText';
```

**Comment by randallwhitman** [comment]
The [create-temporary-function script](https://github.com/Esri/spatial-framework-for-hadoop/blob/master/hive/function-ddl.sql) can be inserted into your `.hiverc` (dot-hiverc) file.

**Comment by vijayasarathib** [comment]
Thanks, its working.
