### ISSUE TITLE
could not replace ST_Contains with between in hive

### ISSUE THREAD

**Issue by vijayasarathib** [Esri/spatial-framework-for-hadoop#74]
i am trying to replace between with the ST_Contains functions.

however query1 and 2 not yielding the same result : 

Query1 : SELECT count(*) FROM src WHERE ((latitude between lat1 and lat2 and longitude between long1 and long2));
query 2 : select count(*) from src where ST_Contains(st_polygon(long1,lat1,long1,lat2,long2,lat1,long2,lat2 );

**Comment by climbage** [comment]
Is that the full second query?  It seems to be missing the second half of `ST_Contains`

**Comment by randallwhitman** [comment]
It looks like the arguments to ST_Polygon are tracing an "N" figure rather than going in order around the perimeter of a box.  Try switching the 6th and 8th arguments:
`st_polygon(long1,lat1,long1,lat2,long2,lat2,long2,lat1 )`

**Comment by vijayasarathib** [comment]
Awesome! It's working, thanks
