### ISSUE TITLE
Framework Documentation

### ISSUE THREAD

**Issue by pacorodrgz** [Esri/spatial-framework-for-hadoop#82]
Hi all,

I'm looking for information about how GIS Tools for Hadoop and its framework really works inside Hadoop, how does the framework modifies Hadoop's core, or if a geometry translation layer is added, or how spatial capabilities are deployed inside Hadoop.

I could only find papers about Hadoop-GIS, which I guess GIS Tools for Hadoop is not based on, right? I'm quite interested on how storage and indexed in HDFS is done, if any spatial data partitioning is required and how queries are translated, optimized and executed as Hive is extended. Is there any modifications for the query engine?

Please, could anyone let me access this information about the framework? My Bachelor's thesis depends on it...

Hope you can help me.

Thanks in advance.

**Comment by randallwhitman** [comment]
Correct, Esri *GIS Tools for Hadoop* framework is distinct from Emory/Ohio *Hadoop-GIS* and from Minnesota *SpatialHadoop*.

There is no white paper nor academic paper on the GIS Tools for Hadoop per se.

The GIS Tools for Hadoop Spatial Framework for Hadoop makes no changes to Hive itself nor to Hadoop itself.  (Thus it can on any Apache or vendor distribution of Hadoop and Hive.)

Source code is available for all of GIS Tools for Hadoop, Apache Hive, and Apache Hadoop.

You may also be interested in:  Randall T. Whitman, Michael B. Park, Sarah M. Ambrose, and Erik G. Hoel. 2014. Spatial indexing and analytics on Hadoop. In *Proceedings of the 22nd ACM SIGSPATIAL International Conference on Advances in Geographic Information Systems* (SIGSPATIAL '14). ACM, New York, NY, USA, 73-82. DOI=10.1145/2666310.2666387 http://doi.acm.org/10.1145/2666310.2666387

**Comment by pacorodrgz** [comment]
Than you so much, that was quite helpful!

**Comment by randallwhitman** [comment]
You're welcome.  If you like, add a link to your thesis in a comment in this issue, once complete.
