### ISSUE TITLE
Magnitude doubts

### ISSUE THREAD

**Issue by pacorodrgz** [Esri/spatial-framework-for-hadoop#83]
Hi all,

I'm using ST_Area and ST_Distance functions but getting values which make no sense in real world. I'm trying to measure some US Counties areas, how could I make it into square miles or square kilometers? May I use WGS84 georeference system?

Thank you.

**Comment by randallwhitman** [comment]
What is the spatial reference of your data?

Can you paste a sample query with expected and actual result?

You may be interested in the [`ST_GeodesicLengthWGS84`](https://github.com/Esri/spatial-framework-for-hadoop/wiki/UDF-Accessors#st_geodesiclengthwgs84) function.
