### ISSUE TITLE
mvn clean install get the following error

### ISSUE THREAD

**Issue by spcrim** [Esri/spatial-framework-for-hadoop#89]
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /home/spark/GITHub/spatial-framework-for-hadoop-master/hive/src/main/java/com/esri/hadoop/hive/ST_IsClosed.java:[3,33] error: package org.apache.commons.logging does not exist

**Comment by randallwhitman** [comment]
Were you building with _ant_ or with _maven_?
Any changes to `build.xml` or `pom.xml`?
What operating system?
Just now I made successful clean ant and maven builds (ant-1.8.2, mvn-3.0.4, OpenJDK-1.7, Ubuntu-12.04/Gnu/Linux-3.2.0/x86-64).

**Comment by spcrim** [comment]
No Changes to POM.xml I am running Hortonworks sandbox Centos 6.5 x86-64 
ant 1.9.6, mvn-3.3.3, java 1.7.0_79 .m2/repository/org/apache/commons doesn't have commons.logging 
BTW thanks for the fast response

**Comment by randallwhitman** [comment]
Thanks for the details, that might help see if it reproduces - what version of Hortonworks Sandbox?

**Comment by spcrim** [comment]
Hortonworks snapbox HDP 2.3

**Comment by smambrose** [comment]
Using:

- Hortonworks sandbox v 2.3_1 with CentOS 6.7
- java javac 1.7.0_85
- maven 3.3.3 

We were not able to reproduce the error. Running mvn clean test we did **not** run into any errors, and had a successful build.

**Comment by spcrim** [comment]
Did you install org.apache.commons.logging?
If so where did you download it and how did you install it?

**Comment by randallwhitman** [comment]
I've been assuming that maven took care of it - I have done nothing special manually to satisfy the dependency.
@smambrose Did you do anything other than `git clone` and `mvn clean test`?

What I have in maven repository cache - in my primary user account:
```
$ ls ~/.m2/repository/org/apache/commons/
commons-compress  commons-exec  commons-lang3  commons-math  commons-math3  commons-parent
```
What I have in a secondary account in which I tested, in order to test in an account that does not have a lot of packages cached:
```
$ ls ~/.m2/repository/org/apache/commons/
commons-compress  commons-math  commons-parent
```

**Comment by randallwhitman** [comment]
After I removed `commons-logging` from the maven repository cache, I re-ran `mvn clean install`; and maven re-downloaded commons-logging and built successfully.  It looks like maven pulls commons-logging as a transitive dependency; however, given we have a direct dependancy, maybe it should be declared in `pom.xml`.  @climbage: any comment about direct/transitive dependencies in maven pom.xml?

@spcrim What is the result if you add the following to pom.xml then try again to build?
```xml
      <dependency>
        <groupId>commons-logging</groupId>
        <artifactId>commons-logging</artifactId>
        <version>1.1.3</version>
      </dependency>
```

**Comment by spcrim** [comment]
/home/spark/.m2/repository/org/apache/commons
I only have      common-parent
But under
/home/spark/.m2/repository/
commons-beanutils, commons-chain, commons-cli, commons-codec, commons-collections, commons-digester, commons-io, commons-lang, commons-logging, commons-validator

Where should I go from here

**Comment by randallwhitman** [comment]
@spcrim Please try pasting in a stanza to the `<dependencies>` section of `pom.xml`:
```xml
      <dependency>
        <groupId>commons-logging</groupId>
        <artifactId>commons-logging</artifactId>
        <version>1.1.3</version>
      </dependency>
```

**Comment by spcrim** [comment]
Under dir “spatial-framework-for-hadoop-master”
Added the commons-logging  dependency in pom.xml
mvn clean install
Got the same results

**Comment by randallwhitman** [comment]
Namely `ST_IsClosed.java:[3,33] error: package org.apache.commons.logging does not exist`.

**Comment by spcrim** [comment]
Yes

**Comment by randallwhitman** [comment]
What happens if you build with `ant` instead of `mvn`?

**Comment by spcrim** [comment]
Ant cause the same error

**Comment by randallwhitman** [comment]
Jar files inside commons-logging?
```
$ ls -l ~/.m2/repository/commons-logging/commons-logging/*/*.jar
-rw-rw-r-- 1 me my 60686 Sep 28 12:25 ~/.m2/repository/commons-logging/commons-logging/1.1.1/commons-logging-1.1.1.jar
```

**Comment by spcrim** [comment]
/home/spark/.m2/repository/commons-logging/commons-logging   contains
1.0  1.0.3  1.0.4  1.1  1.1.1  1.2  commons-logging-1.2.jar  maven-metadata-local.xml

**Comment by smambrose** [comment]
@randallwhitman 

Correct, just git clone and mvn clean test.

**Comment by randallwhitman** [comment]
I do not know what else to try.

**Comment by randallwhitman** [comment]
@spcrim There are [prebuilt JAR binaries on the releases page](https://github.com/Esri/spatial-framework-for-hadoop/releases).

**Comment by spcrim** [comment]
Hey sorry about the late response  I had to run an catch a bus yesterday and problem with mail today
I will try those thing but it look like I got cut off at the proxy now so I have to contact them an see what I can do.

**Comment by spcrim** [comment]
What are the spatial-sdk-hive-1.1.jar and spatial-sdk-json-1.1.jar for?

**Comment by randallwhitman** [comment]
`hive`: [User-Defined Functions and SerDes for spatial analysis in Hive](https://github.com/Esri/spatial-framework-for-hadoop/wiki/Hive-Spatial)
`json`: [Utilities for interacting with JSON exported from ArcGIS](https://github.com/Esri/spatial-framework-for-hadoop/wiki/JSON-Utilities)

**Comment by spcrim** [comment]
Hey Randall 
Maybe you can help me with this problem 
I am getting  a pom error  message when I execute mvn clean install  
I try going to website  http://www.datanucleus.org/downloads/maven2/org/sonatype/oss/oss-parent/7/oss-parent-7.pom and The webpage cannot be found. Is there another website that I can point to?
This is the message I got 
Downloading: http://www.datanucleus.org/downloads/maven2/org/sonatype/oss/oss-parent/7/oss-parent-7.pom
Downloading: https://repo.maven.apache.org/maven2/org/sonatype/oss/oss-parent/7/oss-parent-7.pom
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project com.esri.hadoop:spatial-sdk-hadoop:1.1.1-SNAPSHOT (/home/spark/GITHub/spatial-framework-for-hadoop-master/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM: Could not transfer artifact org.sonatype.oss:oss-parent:pom:7 from/to org.datanucleus (http://www.datanucleus.org/downloads/maven2/): Connect to www.datanucleus.org:80 [www.datanucleus.org/62.75.177.27] failed: Connection refused and 'parent.relativePath' points at wrong local POM @ line 21, column 10 -> [Help 2]

**Comment by randallwhitman** [comment]
@climbage Do you remember what was the purpose of specifying the datanucleus repository in `pom.xml`?  [Looks like now datanucleus host only eclipse and postgis-jdbc](http://www.datanucleus.org/downloads/maven2/org/).

**Comment by climbage** [comment]
There used to be a Hive dependency that wasn't in the main Maven repository, but was in the datanucleus repository.  I don't know whether this is still an issue.

**Comment by spcrim** [comment]
I am not sure what the purpose was but I had recently downloaded the spatial-framework-for-hadoop and it was included in the pom.xml.  I had removed it
and when beyond that point back to my original problem. So I take it there is no need for it.

Spencer Crim

**Comment by randallwhitman** [comment]
In my output from maven, the following indicated that it tried datanucleus.org first, then fell back to repo.maven.apache.org, at which it succeeded - agree or disagree?

```
[INFO] Scanning for projects...
Downloading: http://www.datanucleus.org/downloads/maven2/org/sonatype/oss/oss-pa
rent/7/oss-parent-7.pom
Downloading: http://repo.maven.apache.org/maven2/org/sonatype/oss/oss-parent/7
/oss-parent-7.pom
Downloaded: http://repo.maven.apache.org/maven2
/org/sonatype/oss/oss-parent/7/oss-parent-7.pom (5 KB at 73.6 KB/sec)
```
@spcrim What do you get if you comment-out or remove the part about the datanucleus repository?
```xml
		<!-- repository>
			<id>org.datanucleus</id>
			<name>datanucleus</name>
			<url>http://www.datanucleus.org/downloads/maven2/</url>
		</repository -->
```

**Comment by spcrim** [comment]
It will try to continue to  build the Hive Spatial Framework  and get the org.apache.commons.logging does not exist


mvn clean install
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] Spatial Framework for Hadoop
[INFO] Hive Spatial Framework
[INFO] Spatial JSON Utilities
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Spatial Framework for Hadoop 1.1.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ spatial-sdk-hadoop ---
[INFO]
[INFO] --- maven-enforcer-plugin:1.0:enforce (enforce-maven) @ spatial-sdk-hadoop ---
[INFO]
[INFO] --- maven-install-plugin:2.4:install (default-install) @ spatial-sdk-hadoop ---
[INFO] Installing /home/spark/GITHub/spatial-framework-for-hadoop-master/pom.xml to /home/spark/.m2/repository/com/esri/hadoop/spatial-sdk-hadoop/1.1.1-SNAPSHOT/spatial-sdk-hadoop-1.1.1-SNAPSHOT.pom
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Hive Spatial Framework 1.1.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ spatial-sdk-hive ---
[INFO] Deleting /home/spark/GITHub/spatial-framework-for-hadoop-master/hive/target
[INFO]
[INFO] --- maven-enforcer-plugin:1.0:enforce (enforce-maven) @ spatial-sdk-hive ---
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ spatial-sdk-hive ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/spark/GITHub/spatial-framework-for-hadoop-master/hive/src/main/resources
[INFO]
[INFO] --- maven-compiler-plugin:2.3.2:compile (default-compile) @ spatial-sdk-hive ---
[INFO] Compiling 93 source files to /home/spark/GITHub/spatial-framework-for-hadoop-master/hive/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /home/spark/GITHub/spatial-framework-for-hadoop-master/hive/src/main/java/com/esri/hadoop/hive/ST_IsClosed.java:[3,33] error: package org.apache.commons.logging does not exist

**Comment by randallwhitman** [comment]
If inside `<dependencies>` you add the following dependency, then what happens?
```xml

      <dependency>
        <groupId>commons-logging</groupId>
        <artifactId>commons-logging</artifactId>
        <version>${logging.version}</version>
      </dependency>
```

**Comment by spcrim** [comment]
Unfortunately I get the same error.

**Comment by randallwhitman** [comment]
Unfortunate indeed, that seems to refute the obvious candidate for an easy fix.

**Comment by GISDev01** [comment]
@spcrim Only 1 thing interesting that might be a clue here. 
Originally you mentioned: 
'commented on Sep 21 - I am running Hortonworks sandbox Centos 6.5 x86-64 "
Then you mentioned: 
'commented on Sep 21 - Hortonworks sandbox HDP 2.3"

As far as I know, the HDP 2.3 VM runs on only CentOS 6.7, so perhaps you grabbed a VM before Hortonworks updated the OS or you're running an older version of the HDP VM?

First thing I would try if I were you, is to re-download the latest HDP 2.3 VM (the same one  @smambrose used to test on Sept. 23rd), and then give this a shot again on the brand new HDP 2.3 VM and let us know the exact steps you take from when you fire up the VM for the first time, to when you run 'mvn clean install'. 

99% chance we can easily debug any issues then.

**Comment by randallwhitman** [comment]
The datanucleus repo is used for javax.jdo:jdo2-api:jar:2.3-ec with hive-.11

**Comment by randallwhitman** [comment]
Any reason to keep this issue open?

**Comment by smambrose** [comment]
seems pretty safe to close...

**Comment by spcrim** [comment]
No

Spencer Crim
IT Specialist
Civil Rights Division
600 E St. N.W Rm 3528
(202)353-9267
