### ISSUE TITLE
Publishing geoprocessing service

### ISSUE THREAD

**Issue by kc-lee** [Esri/spatial-framework-for-hadoop#92]
Hi,

I created a Model and and ran it as a tool. From the results, I tried to publish it to my server as a geoprocesing service so that I can consume it from webappbuilder. But it failed.
![capture](https://cloud.githubusercontent.com/assets/16011826/11491805/474ea28c-9820-11e5-8fef-bd70ef01cd17.PNG)

I have 10.3.1 server, 10.3.1 desktop and Hortonworks 2.3.2 VM running locally. 

Is this supported?

**Comment by randallwhitman** [comment]
Curious whether the reason for closing the issue, is success, versus giving up.

**Comment by kc-lee** [comment]
thanks for looking at it, I posted this under the wrong branch. I re-posted it under geoprocessing-tools-for-hadoop where I faced the issue. Thanks.
